# Generated by Django 6.0.8 on 2026-08-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('CHEF_AGENCE_COMMERCIALE', "Chef d'agence commerciale"), ('CHEF_AGENCE_ANALYSE', "Chef d'agence analyse"), ('ANALYSTE', 'Analyste Engagement'), ('DIRECTION', 'Direction'), ('COMITE', 'Comité'), ('ADMINISTRATEUR', 'Administrateur')], default='COMMERCIAL', max_length=30, verbose_name='Rôle'),
        ),
    ]
