# Generated by Django 6.0.8 on 2026-08-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame')], max_length=3)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Camerounaise', max_length=100)),
                ('numero_cni', models.CharField(max_length=50, unique=True, verbose_name='Numéro CNI')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('type_employeur', models.CharField(choices=[('FONCTIONNAIRE', 'Fonctionnaire'), ('PRIVE', 'Secteur privé'), ('ONG', 'ONG / Association'), ('COMMERCANT', 'Commerçant'), ('RETRAITE', 'Retraité'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'employeur")),
                ('nom_employeur', models.CharField(max_length=150, verbose_name="Nom de l'employeur")),
                ('poste_occupe', models.CharField(max_length=100, verbose_name='Poste occupé')),
                ('anciennete', models.PositiveIntegerField(verbose_name='Ancienneté (années)')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire net mensuel (FCFA)')),
                ('charges_mensuelles', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Charges mensuelles (FCFA)')),
                ('credits_en_cours', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédits en cours (FCFA)')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_credit', models.CharField(choices=[('EQUIPEMENT', 'Crédit équipement'), ('SCOLAIRE', 'Crédit scolaire'), ('BAIL', 'Crédit-bail'), ('CONSOMMATION', 'Crédit consommation'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de crédit')),
                ('montant_sollicite', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant sollicité (FCFA)')),
                ('duree_mois', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('objet_financement', models.TextField(verbose_name='Objet du financement')),
                ('appreciation', models.TextField(help_text='Observations et avis du commercial sur le dossier', verbose_name='Appréciation du commercial')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', "Soumis au chef d'agence"), ('VALIDE_CHEF', "Validé par le chef d'agence"), ('EN_ANALYSE', "En cours d'analyse"), ('ANALYSE_TERMINEE', 'Analyse terminée'), ('VALIDE_DIRECTION', 'Validé par la direction'), ('EN_COMITE', 'En attente du comité'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=25, verbose_name='Statut')),
                ('necessite_comite', models.BooleanField(default=False, verbose_name='Nécessite le comité')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('soumis_le', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='dossiers.client', verbose_name='Client')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=15)),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='dossiers.dossier', verbose_name='Dossier')),
                ('validateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': 'Validation',
                'verbose_name_plural': 'Validations',
                'ordering': ['date'],
            },
        ),
    ]
