# Generated by Django 6.0.8 on 2026-08-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CNI', 'Photocopie CNI'), ('RIB', "Relevé d'identité bancaire (RIB)"), ('HISTORIQUE_BANQUE', 'Historique de compte (3 derniers mois)'), ('NIU', "Attestation d'immatriculation (NIU)"), ('AUTRE', 'Autre document')], max_length=20, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='dossiers/documents/%Y/%m/', verbose_name='Fichier')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('uploade_le', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossier', verbose_name='Dossier')),
                ('uploade_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['type_document'],
            },
        ),
    ]
