# Generated by Django 6.0.8 on 2026-08-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_documentdossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_versement_salaire',
            field=models.PositiveIntegerField(blank=True, help_text='Jour habituel de réception du salaire (ex: 15 pour le 15 du mois)', null=True, verbose_name='Jour de versement du salaire'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_debut_prelevement',
            field=models.DateField(blank=True, help_text='Date convenue avec le client pour le début des remboursements', null=True, verbose_name='Date de début de prélèvement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='jour_prelevement',
            field=models.PositiveIntegerField(blank=True, help_text='Jour du mois auquel le client sera prélevé (ex: 25 pour le 25 de chaque mois)', null=True, verbose_name='Jour de prélèvement mensuel'),
        ),
    ]
