# Generated by Django 6.0.8 on 2026-08-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_client_date_versement_salaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='client',
            name='mode_paiement',
            field=models.CharField(default='PSMA', help_text='PSMA = Prélèvement Sur Masse Salariale Automatique', max_length=10, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='assureur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assureur'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='avi',
            field=models.BooleanField(default=False, verbose_name='AVI (Avis de Virement Irrévocable)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='delegation_salaire',
            field=models.BooleanField(default=False, verbose_name='Délégation de salaire'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='echeance_mens_banque',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Engagements mensuels du client dans d'autres banques", max_digits=12, verbose_name='Echéance mensuelle banque (FCFA)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='encours_sce',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Total restant dû à la SCE sur d'anciens dossiers", max_digits=14, verbose_name='Encours SCE (FCFA)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='montant_assurance_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant assurance TTC (FCFA)'),
        ),
    ]
