# Generated by Django 6.0.8 on 2026-08-14 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_client_matricule_client_mode_paiement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='fiche2_verrouillee',
            field=models.BooleanField(default=False, help_text='True dès que le dossier est soumis', verbose_name='Fiche 2 verrouillée'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='mode_paiement',
            field=models.CharField(default='PSMA', max_length=10, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='releve_analyse_ok',
            field=models.BooleanField(null=True, verbose_name='Relevé conforme'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='releve_banque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banque détectée sur relevé'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='releve_decouvert',
            field=models.BooleanField(default=False, verbose_name='Découvert détecté sur relevé'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='releve_raisons_refus',
            field=models.TextField(blank=True, verbose_name='Raisons de non-conformité'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='releve_remboursements',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Remboursements crédits détectés (FCFA/mois)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='releve_solde_moyen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Solde moyen relevé (FCFA)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='releve_total_credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total crédits relevé 3 mois (FCFA)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='releve_total_debits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total débits relevé 3 mois (FCFA)'),
        ),
        migrations.AddField(
            model_name='validationdossier',
            name='assigne_a',
            field=models.ForeignKey(blank=True, help_text='Analyste à qui ce dossier est assigné pour cette étape', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AddField(
            model_name='validationdossier',
            name='etape',
            field=models.CharField(choices=[('VISA_CHEF_AGENCE', "1ère signature Chef d'agence"), ('AVIS_ANALYSTE1', 'Avis Analyste 1'), ('AVIS_ANALYSTE2', 'Avis Analyste 2'), ('VISA_CHEF_ANALYSTE', "2ème signature Chef d'analyste"), ('DECISION_DIR', 'Décision Direction'), ('DECISION_COMITE', 'Décision Comité')], default='VISA_CHEF_AGENCE', max_length=20, verbose_name='Étape du circuit'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='appreciation',
            field=models.TextField(blank=True, verbose_name='Appréciation du commercial'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='avi',
            field=models.BooleanField(default=False, verbose_name='AVI'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='date_debut_prelevement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début de prélèvement'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='echeance_mens_banque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Echéance mensuelle banque (FCFA)'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='encours_sce',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Encours SCE (FCFA)'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='jour_prelevement',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jour de prélèvement mensuel'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ANALYSE_RELEVE', 'Analyse du relevé en cours'), ('NON_CONFORME', 'Dossier non conforme'), ('PRET_A_SOUMETTRE', 'Prêt à soumettre'), ('SOUMIS', "Soumis au chef d'agence"), ('VALIDE_CHEF_1', "Validé chef d'agence (1ère signature)"), ('EN_ANALYSE_1', "En cours d'analyse (Analyste 1)"), ('EN_ANALYSE_2', "En cours d'analyse (Analyste 2)"), ('ANALYSE_TERMINEE', 'Analyses terminées'), ('VALIDE_CHEF_2', "Validé chef d'agence (2ème signature)"), ('EN_DECISION', 'En attente de décision direction'), ('EN_COMITE', 'En attente du comité'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=25, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='validationdossier',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire / Avis'),
        ),
        migrations.CreateModel(
            name='HistoriqueSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire net (FCFA)')),
                ('date_effet', models.DateField(verbose_name="Date d'effet")),
                ('note', models.CharField(blank=True, help_text='Ex: Promotion, revalorisation, changement de poste', max_length=200, verbose_name='Note')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_salaires', to='dossiers.client', verbose_name='Client')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Historique salaire',
                'verbose_name_plural': 'Historiques salaires',
                'ordering': ['-date_effet'],
            },
        ),
        migrations.CreateModel(
            name='ImpayeSCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_impaye', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant impayé (FCFA)')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance manquée")),
                ('date_regularisation', models.DateField(blank=True, null=True, verbose_name='Date de régularisation')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('REGULARISE', 'Régularisé'), ('CONTENTIEUX', 'En contentieux')], default='EN_COURS', max_length=15, verbose_name='Statut')),
                ('nb_mois_retard', models.PositiveIntegerField(default=0, verbose_name='Nombre de mois de retard')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impayes', to='dossiers.client', verbose_name='Client')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impayes', to='dossiers.dossier', verbose_name='Dossier concerné')),
            ],
            options={
                'verbose_name': 'Impayé SCE',
                'verbose_name_plural': 'Impayés SCE',
                'ordering': ['-date_echeance'],
            },
        ),
    ]
