# Generated by Django 6.0.8 on 2026-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_dossier_fiche2_verrouillee_dossier_mode_paiement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='releve_analyse_ok',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='releve_banque',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='releve_decouvert',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='releve_raisons_refus',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='releve_remboursements',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='releve_solde_moyen',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='releve_total_credits',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='releve_total_debits',
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PRET_A_SOUMETTRE', 'Prêt à soumettre'), ('SOUMIS', "Soumis au chef d'agence"), ('VALIDE_CHEF_1', "Validé chef d'agence (1ère signature)"), ('EN_ANALYSE_1', "En cours d'analyse (Analyste 1)"), ('EN_ANALYSE_2', "En cours d'analyse (Analyste 2)"), ('ANALYSE_TERMINEE', 'Analyses terminées'), ('VALIDE_CHEF_2', "Validé chef d'agence (2ème signature)"), ('EN_DECISION', 'En attente de décision direction'), ('EN_COMITE', 'En attente du comité'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=25, verbose_name='Statut'),
        ),
    ]
