# Generated by Django 6.0.8 on 2026-08-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('DOCUMENTS_INCOMPLETS', 'Documents incomplets'), ('PRET_A_SOUMETTRE', 'Prêt à soumettre'), ('SOUMIS', "Soumis au chef d'agence"), ('VALIDE_CHEF_1', "Validé chef d'agence (1ère signature)"), ('EN_ANALYSE_1', "En cours d'analyse (Analyste 1)"), ('EN_ANALYSE_2', "En cours d'analyse (Analyste 2)"), ('ANALYSE_TERMINEE', 'Analyses terminées'), ('VALIDE_CHEF_2', "Validé chef d'agence (2ème signature)"), ('EN_DECISION', 'En attente de décision direction'), ('EN_COMITE', 'En attente du comité'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=25, verbose_name='Statut'),
        ),
    ]
