# Generated by Django 6.0.8 on 2026-08-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0008_alter_dossier_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('DOCUMENTS_INCOMPLETS', 'Documents incomplets'), ('PRET_A_SOUMETTRE', 'Prêt à soumettre'), ('SOUMIS', "Soumis au chef d'agence"), ('VALIDE_CHEF_COMMERCIAL', "Validé chef d'agence commerciale"), ('EN_ANALYSE_1', "En cours d'analyse (Analyste 1)"), ('EN_ANALYSE_2', "En cours d'analyse (Analyste 2)"), ('ANALYSE_TERMINEE', 'Analyses terminées'), ('VALIDE_CHEF_ANALYSTE', "Validé chef d'agence analyse"), ('EN_DECISION', 'En attente de décision direction'), ('EN_COMITE', 'En attente du comité'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=25, verbose_name='Statut'),
        ),
    ]
