# Generated by Django 6.0.8 on 2026-08-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0003_client_date_versement_salaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Score de solvabilité calculé par le modèle IA', verbose_name='Score (/100)')),
                ('niveau_risque', models.CharField(choices=[('FAIBLE', 'Risque faible'), ('MOYEN', 'Risque moyen'), ('ELEVE', 'Risque élevé'), ('CRITIQUE', 'Risque critique')], max_length=10, verbose_name='Niveau de risque')),
                ('decision_ia', models.CharField(choices=[('FAVORABLE', 'Favorable'), ('CONDITIONNEL', 'Favorable sous conditions'), ('DEFAVORABLE', 'Défavorable')], max_length=15, verbose_name='Décision IA')),
                ('taux_endettement', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'endettement (%)")),
                ('ratio_mensualite_salaire', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ratio mensualité / salaire (%)')),
                ('delai_securite', models.IntegerField(help_text='Écart entre le jour de salaire et le jour de prélèvement', verbose_name='Délai de sécurité (jours)')),
                ('score_stabilite_emploi', models.PositiveIntegerField(help_text="Basé sur le type d'employeur et l'ancienneté", verbose_name='Score stabilité emploi (/25)')),
                ('score_capacite_remboursement', models.PositiveIntegerField(help_text="Basé sur le taux d'endettement et le ratio mensualité/salaire", verbose_name='Score capacité de remboursement (/25)')),
                ('score_profil_client', models.PositiveIntegerField(help_text="Basé sur l'âge, l'ancienneté et le délai de sécurité", verbose_name='Score profil client (/25)')),
                ('score_dossier', models.PositiveIntegerField(help_text='Basé sur la complétude des documents et le type de crédit', verbose_name='Score dossier (/25)')),
                ('recommandation_ia', models.TextField(blank=True, help_text='Analyse narrative générée par Gemini API', verbose_name='Recommandation IA')),
                ('conditions_proposees', models.TextField(blank=True, help_text="Conditions suggérées par l'IA si décision conditionnelle", verbose_name='Conditions proposées')),
                ('calcule_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Score de crédit',
                'verbose_name_plural': 'Scores de crédit',
            },
        ),
    ]
