# Generated by Django 6.0.8 on 2026-08-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecredit',
            name='conditions_proposees',
        ),
        migrations.RemoveField(
            model_name='scorecredit',
            name='recommandation_ia',
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='conditions',
            field=models.TextField(blank=True, help_text='Conditions suggérées si décision conditionnelle', verbose_name='Conditions proposées'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='recommandation',
            field=models.TextField(blank=True, help_text='Analyse générée par le moteur de scoring SCE', verbose_name='Recommandation'),
        ),
    ]
