# Generated by Django 6.0.8 on 2026-08-28 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_alter_dossier_statut'),
        ('scoring', '0002_remove_scorecredit_conditions_proposees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecredit',
            name='score_capacite_remboursement',
        ),
        migrations.RemoveField(
            model_name='scorecredit',
            name='score_profil_client',
        ),
        migrations.RemoveField(
            model_name='scorecredit',
            name='score_stabilite_emploi',
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='eligible',
            field=models.BooleanField(default=True, verbose_name='Dossier éligible (a passé le gardien)'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='motif_ineligibilite',
            field=models.TextField(blank=True, verbose_name="Motif d'inéligibilité"),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='score_fidelite',
            field=models.PositiveIntegerField(default=0, verbose_name='Score fidélité relation (/10)'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='score_historique_sce',
            field=models.PositiveIntegerField(default=0, verbose_name='Score historique SCE (/20)'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='score_marge_securite',
            field=models.PositiveIntegerField(default=0, verbose_name='Score marge de sécurité (/5)'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='score_montant_vs_salaire',
            field=models.PositiveIntegerField(default=0, verbose_name='Score montant vs salaire (/15)'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='score_quotite',
            field=models.PositiveIntegerField(default=0, verbose_name='Score quotité (/25)'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='score_stabilite',
            field=models.PositiveIntegerField(default=0, verbose_name='Score stabilité revenu (/15)'),
        ),
        migrations.AlterField(
            model_name='scorecredit',
            name='decision_ia',
            field=models.CharField(choices=[('FAVORABLE', 'Favorable'), ('CONDITIONNEL', 'Favorable sous conditions'), ('DEFAVORABLE', 'Défavorable'), ('INELIGIBLE', 'Inéligible (bloqué avant analyse)')], max_length=15, verbose_name='Décision IA'),
        ),
        migrations.AlterField(
            model_name='scorecredit',
            name='score_dossier',
            field=models.PositiveIntegerField(default=0, verbose_name='Score complétude dossier (/10)'),
        ),
        migrations.CreateModel(
            name='TraceDecisionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(max_length=30, verbose_name='Étape du circuit')),
                ('score_fige', models.PositiveIntegerField(verbose_name='Score figé (/100)')),
                ('niveau_risque_fige', models.CharField(max_length=10, verbose_name='Niveau de risque figé')),
                ('decision_ia_figee', models.CharField(max_length=15, verbose_name='Décision IA figée')),
                ('score_regles_fige', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score règles métier (avant fusion ML)')),
                ('score_ml_fige', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score ML brut (probabilité de remboursement, %)')),
                ('version_modele_ml', models.CharField(blank=True, max_length=50, verbose_name='Version du modèle ML utilisé')),
                ('decision_humaine', models.CharField(max_length=10, verbose_name='Décision humaine (APPROUVE/REJETE)')),
                ('desaccord', models.BooleanField(default=False, help_text='True si la décision humaine contredit la recommandation IA', verbose_name='Désaccord IA / humain')),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces_decision_ia', to='dossiers.dossier', verbose_name='Dossier')),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': 'Trace de décision IA',
                'verbose_name_plural': 'Traces de décisions IA',
                'ordering': ['-date_decision'],
            },
        ),
    ]
