# Generated by Django 6.0.8 on 2026-08-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_remove_scorecredit_score_capacite_remboursement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecredit',
            name='facteurs_ml',
            field=models.JSONField(blank=True, default=list, verbose_name='Facteurs déterminants du modèle ML'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='score_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score ML brut (probabilité remboursement %)'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='score_regles',
            field=models.PositiveIntegerField(default=0, verbose_name='Score règles métier seul (/100)'),
        ),
        migrations.AddField(
            model_name='scorecredit',
            name='version_modele_ml',
            field=models.CharField(blank=True, max_length=50, verbose_name='Version du modèle ML utilisé'),
        ),
    ]
